language: go
sudo: required
go_import_path: cirello.io/qrng
go:
  - "1.16"

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

install: true

script:
  - go test -v . -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci